module.exports = {
  name: 'find',
  description: [
    'Search CenzoJS function docs.',
    'Usage:',
    '  !find                — full category overview',
    '  !find $functionName  — look up a specific function',
    '  !find <category>     — list all functions in a category',
    '',
    'Categories:',
    '  discord  message  moderation  roles  channels',
    '  variables  database  control  logic',
    '  math  strings  embeds  components',
    '  time  cooldown  reactions  emojis  random',
    '  http  webhooks  threads  permissions  errorhandling  blacklist  misc',
    '',
    '  !find <keyword>      — search by keyword in name or description',
  ].join('\n'),
  code: '$find[$noMentionMessage]',
};
